#!/usr/bin/env python
# -*- coding: utf-8 -*-

from getpass import getpass
from mechanize import Browser
from cmd import Cmd
import json

class OwnCloudClient:
	"""OwncloudClient"""

	isLoggedIn = False
	isConnected = False
	actualDir='/'

	def __init__(self):
		self.br = Browser()

	def getResponse(self):
		return br.response().read().split('\n')

	def connect(self, server_addr):

		self.server = server_addr
		self.br.open('https://' + server_addr)
		#self.isConnected = br.open('https://' + server_addr)
		#return self.isConnected

	def disconnect(self):
		print "TODO"

	def login(self, username, password):
		if (not self.isLoggedIn):
			self.br.select_form(name='login')
			self.br.form['user'] = username
			self.br.form['password'] = password
			self.br.submit()
		else:
			print "TODO: login (username=%s, password=%s)" % (username, password)

	def logout(self):
		print "TODO: logout"

	def createFolder(self, foldername):
		
		self.br.select_form(nr=0)
		self.br.form.controls.pop()
		self.prepareNewForm(self.br)
		self.br.form.new_control('text', 'dir', {})
		self.br.form['dir'] = u'/'
		self.br.form.new_control('text', 'foldername', {})
		self.br.form['foldername'] = foldername
		self.br.form.action = 'https://cloud.iip.ufrn.br/index.php/apps/files/ajax/newfolder.php'

		self.br.submit()
		self.br.back()

	def list(self, directory):
		
		self.br.select_form(nr=0)
		#self.br.form.controls.pop()
		self.prepareNewForm(self.br)
		self.br.form.action = 'https://cloud.iip.ufrn.br/index.php/apps/files/ajax/list.php?dir=%2F&soft=name&sortdirection=asc'
		self.br.form.method = 'GET'
		self.br.form.new_control('text', 'dir', {})
		self.br.form['dir'] = u'/'

		self.br.submit()

		#print self.br.response().read().split('\n')
		for i in self.br.response().read().split('\n'):
			if '\"data\":' in i:
				json_acceptable_string = i.replace("'", "\"")
				d = json.loads(json_acceptable_string)
				#print d
				for j in d[u'data'][u'files']:
					print j['type'] + '\t' + j['name']
				#for j in i[0]['data']['files']:
				#	print j['type'] + '\t' + j['name']
		self.br.back()
	
	def prepareNewForm(self, browser):
	
		for i in browser.response().read().split('\n'):
			if 'data-requesttoken' in i:
				token = i.split('=')[2][1:-2]

		browser.form.new_control('text', 'Accept', {})
		browser.form['Accept'] = '*/*'
		browser.form.new_control('text', 'requesttoken', {})
		browser.form['requesttoken'] = token
		browser.form.new_control('text', 'Refer', {})
		browser.form['Refer'] = 'https://cloud.iip.ufrn.br/index.php/app/files/'
		browser.form.new_control('text', 'Origin', {})
		browser.form['Origin'] = 'https://cloud.iip.ufrn.br'
		browser.form.new_control('text', 'X-Requested-With', {})
		browser.form['X-Requested-With'] = 'XMLHttpRequest'
		browser.form.new_control('text', 'Content-Type', {})
		browser.form['Content-Type'] = 'application/x-www-form-urlencoded; charset=UTF-8'

	def removeFolder(self, foldername):
		print "TODO: remove folder %s" % foldername

	def uploadFile(self, localFilePath):
		print "TODO: uploadfile %s" % localFilePath

	def downloadFile(self, filename):
		print 'TODO: downloadfile %s' % filename

	def removeFile(self, filename):
		print "TODO: removeFile %s" % filename


class OwnCloudCmd(Cmd):
	"""Simple example of a command processor."""

	oc = OwnCloudClient()

	def do_list(self, line):
		args = line.split(' ')
		#command = args[0]
		if len(args) > 2 and len(args) < 1:
			print self.help_list()
		if len(args) == 2:
			dir = args[1]
		elif len(args) == 1:
			dir = u'/'
			## TODO Enable listing other directories
		self.oc.list(dir)

	def do_connect(self, line):
		args = line.split(' ')
		if len(args) == 1:
			server_addr = args[0]
			self.oc.connect(server_addr)
			self.prompt = '%s ~> ' % server_addr
		else:
			print self.help_create()

	def do_login(self, line):
		args = line.split(' ')
		if len(args) == 2:
			u = args[0]
			p = args[1]
			self.oc.login(u, p)
			## TODO Test it
			self.prompt = u + '@' + self.prompt[:-3] + '#> '
		else:
			print self.help_login()


	def do_create(self, line):

		# TODO Check args length 
		if len(line) == 0:
			print self.help_create()
		else:
			args=line.split(' ')
			if len(args[0]) == 0:
				print self.help_create()
			elif args[0] == 'folder':
				self.oc.createFolder(args[1])
			elif args[0] == 'text_file':
				print "CREATE TEXT FILE"
			elif args[0] == 'from_link':
				print "CREATE FROM LINK"
			else:
				print self.help_create()
	

	def do_exit(self, line):
		print "Saindo. "
		#sleep(1)
		raise SystemExit

	def help_create(self):
		return 'HELP CREATE'

	def help_login(self):
		return 'HELP LOGIN'
	
	def help_list(self):
		return 'HELP LIST'


class CmdUI():
	"""CmdUI"""

	prompt = OwnCloudCmd()

	def __init__(self, server, user, passwd):
		self.prompt.prompt = 'OCClient > '
		self.prompt.do_connect(server)
 		self.prompt.do_login(user + ' ' + passwd)
		self.prompt.cmdloop()


if __name__ == '__main__':
	server = str(raw_input('Server (https): '))

	## TODO Improve check through regexp
	## TODO check if it's a valid DNS NAME or IP ADDRESS
	if (server[:7] == 'http://'):
		server = server[:7]
	elif (server[:8] == 'https://'):
		server = server[:8]

	user = str(raw_input('Username: '))
	passwd = getpass('Password: ')
	#CmdUI('cloud.iip.ufrn.br', 'registration', '123')
	CmdUI(server, user, passwd)
